approot/src/MandirDarsan/Areas/Admin/Controllers/CulturesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Mvc;
using Microsoft.Extensions.PlatformAbstractions;
using Microsoft.Net.Http.Headers;
using PagedList;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
using Microsoft.AspNet.Identity;
using MandirDarsan.Areas.Admin.Models;
using MandirDarsan.Models;
namespace MandirDarsan.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    [Area("Admin")]
    public class CulturesController : Controller
	{
		
        string pathToCreate = "Images\\Culture";
        IApplicationEnvironment _hostingEnvironment;
        private static ApplicationDbContext _context;
        private RockmanduBase rBase = new RockmanduBase();
        private ICulture cultureRepository;
        public CulturesController(ApplicationDbContext context, IApplicationEnvironment hostingEnvironment)
        {
            _context = context;
            _hostingEnvironment = hostingEnvironment;
            cultureRepository =new CultureRepository(_context);
        }

        // GET: Admin/Cultures
        public ActionResult Index(int? pageNo, string searchTerm="")
        {
            ViewBag.DashboardSegment = "admin";
            ViewBag.DashboardSubSegment = "cultures";

            var culture = cultureRepository.GetAll().Where(x=>x.Title.ToLower().Contains(searchTerm.ToLower()));
			int totalPageSize = rBase.GetPageSize();
            var noOfPage = (pageNo ?? 1);
			return View(culture.ToPagedList(noOfPage ,totalPageSize ));
        }
    
        // GET: Admin/Cultures/Create
        public ActionResult Create()
        {
            ViewBag.DashboardSegment = "admin";
            ViewBag.DashboardSubSegment = "cultures";
            return View();
        }

        // POST: Admin/Cultures/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		
        			public ActionResult Create(Culture culture)
		
        {
            if (ModelState.IsValid)
            {
				culture.CreatedBy =  User.Identity.Name;
                culture.ModifiedBy = User.Identity.Name;
        			    
			
				
                cultureRepository.Add(culture, User.Identity.Name);
                cultureRepository.Commit();
                return RedirectToAction("Index");
            }

            return View(culture);
        }

        public ActionResult Edit(Guid id)
        {
            ViewBag.DashboardSegment = "admin";
            ViewBag.DashboardSubSegment = "cultures";
            var culture = cultureRepository.GetSingle(id);
            if (culture == null)
            {
                return HttpNotFound();
            }    
            return View(culture);
        }

        // POST: Admin/Cultures/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
		
					public ActionResult Edit(Culture culture)
		
		
        {
            if (ModelState.IsValid)
            {
                if (User.IsInRole("Admin") || culture.CreatedBy == User.Identity.Name)
                {
                    culture.ModifiedBy = User.Identity.Name;
                    cultureRepository.Edit(culture,User.Identity.Name);
                    cultureRepository.Commit();
                    _context.SaveChanges();
                }
                return RedirectToAction("Index");
            }
            return View(culture);
        }
        public ActionResult Trash(int? pageNo)
        {
            ViewBag.DashboardSegment = "admin";
            ViewBag.DashboardSubSegment = "cultures";
            var culture = cultureRepository.GetAllDeleted(User.Identity.Name);
             var noOfPage = (pageNo ?? 1);
            int totalPageSize = rBase.GetPageSize();
            return View(culture.ToPagedList(noOfPage, totalPageSize));
        }
        [HttpPost, ActionName("RecoverTrash")]
        [ValidateAntiForgeryToken]
        public ActionResult RecoverFromTrash(Guid id)
        {
            var culture = cultureRepository.GetSingle(id);
            cultureRepository.Undelete(culture);
            cultureRepository.Commit();
           return RedirectToAction("Trash");
        }
        [HttpPost, ActionName("DeleteTrash")]
        [ValidateAntiForgeryToken]
        public ActionResult EmptyTrash()
        {
            IEnumerable<Culture> culture = cultureRepository.GetAllDeleted(User.Identity.Name);
            foreach (var items in culture)
            {
                cultureRepository.ConfirmDelete(items.Id);
            }
            cultureRepository.Commit();
           return RedirectToAction("Trash");
        }
        public ActionResult DeleteTrashItem(Guid id)
        {
            cultureRepository.ConfirmDelete(id);
            cultureRepository.Commit();
            ViewBag.Message = "Item Permanently Deleted";
           return RedirectToAction("Trash");
        }
		  [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(Guid id)
        {
            var  culture =  cultureRepository.GetSingle(id);
             cultureRepository.Delete( culture);
             cultureRepository.Commit();
             cultureRepository.Commit();
            return RedirectToAction("Index");
        }
       protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                _context.Dispose();
            }
            base.Dispose(disposing);
        }
        [Authorize(Roles = ("Admin"))]
        public ActionResult UnVerified(int? pageNo)
        {
            int totalPageSize = rBase.GetPageSize();
            var noOfPage = (pageNo ?? 1);
            return View(cultureRepository.GetAllUnVerified().ToPagedList(noOfPage, totalPageSize));
        }
        [Authorize(Roles = ("Admin"))]
        [HttpPost]
        public ActionResult Verify(string id)
        {

            var unverifiedGod = cultureRepository.GetSingle(Guid.Parse(id));
            cultureRepository.Verify(unverifiedGod, User.Identity.Name);
            cultureRepository.Commit();
            return RedirectToAction("Unverified");
        }
    }
}

approot/src/MandirDarsan/Controllers/ShoppingCartController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MandirDarsan.Models;
using MandirDarsan.ViewModels.Mandir;
using Microsoft.AspNet.Antiforgery;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Http.Internal;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Microsoft.Extensions.Primitives;
namespace MandirDarsan.Controllers
{
    public class ShoppingCartController : Controller
    {
        [FromServices]
        public ApplicationDbContext DbContext { get; set; }
        public ShoppingCartController (ApplicationDbContext db)
        {
            DbContext = db;
        }
        [FromServices]
        public IAntiforgery Antiforgery { get; set; }

        //
        // GET: /ShoppingCart/
        public async Task<IActionResult> Index(string culture)
        {
            var cart = ShoppingCart.GetCart(DbContext, HttpContext);
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = await cart.GetCartItems(),
                CartTotal = await cart.GetTotal()
            };
            if (viewModel.CartItems.Count == 0)
            {

                return Redirect("~/" + culture + "/Store");
                //Redirect("http://mandirdarsan.com/" + culture + "/Store");
            }
            return View(viewModel);
        }
        //
        // GET: /ShoppingCart/AddToCart/5
        public async Task<IActionResult> AddToCart(Guid id, int qty, CancellationToken requestAborted,IFormCollection formCollection)
        {

            // Retrieve the album from the database
            //if (qty == 0) { 
            //    qty = Convert.ToInt32(formCollection.Where(x => x.Key == "qty").Select(x => x.Value).SingleOrDefault());
            //}

            var addedAlbum = DbContext.Products
                .Single(album => album.Id == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(DbContext, HttpContext);

           // cart.AddToCart(addedAlbum.ProductId,qty);
            if (qty == 0)
            {
                qty = 1;
            }
            cart.AddToCart(addedAlbum.Id, qty);

            await DbContext.SaveChangesAsync(requestAborted);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(Guid id, CancellationToken requestAborted)
        {
            var cookieToken = string.Empty;
            var formToken = string.Empty;
            StringValues tokenHeaders;
            string[] tokens = null;

            if (HttpContext.Request.Headers.TryGetValue("RequestVerificationToken", out tokenHeaders))
            {
                tokens = tokenHeaders.First().Split(':');
                if (tokens != null && tokens.Length == 2)
                {
                    cookieToken = tokens[0];
                    formToken = tokens[1];
                }
            }
            try
            {
                Antiforgery.ValidateTokens(HttpContext, new AntiforgeryTokenSet(formToken, cookieToken));
            }
            catch (Exception)
            {
            }
            

            var cart = ShoppingCart.GetCart(DbContext, HttpContext);
            try
            {
                var cartItem = DbContext.Carts
                    .Where(item => item.ProductId == id).Include(x=>x.Product);
               
           
           

            int itemCount = cart.RemoveFromCart(id);

            await DbContext.SaveChangesAsync(requestAborted);

            string removed = (itemCount > 0) ? " 1 copy of " : string.Empty;
            
            var results = new ShoppingCartRemoveViewModel
            {
                Message = removed + /*cartItem.Product.Title +*/
                    " has been removed from your shopping cart.",
                CartTotal = await cart.GetTotal(),
                CartCount = await cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
                return Json(results);
            }
            catch (Exception ex)
            {

                throw;
            }
           
        }
    }
}

approot/src/MandirDarsan/Views/Shared/AccessDenied.cshtml
@{
    ViewBag.Title = "Access denied due to insufficient permissions";
}
<h1 class="text-danger" translate>Access denied due to insufficient permissions.</h1>

approot/src/MandirDarsan/Views/Shared/_AuditJs.cshtml
<div id="myModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Changes</h4>
            </div>
            <div class="modal-body">
                <div id="audit"></div>
            </div>
            <div class="modal-footer">

                @*<form method="POST" id="AuditIdForm" class="form-horizontal" role="form" asp-anti-forgery="true">*@
                <button type="button" class="btn btn-primary" onclick="showauditmodal()">Show Detailed Changes</button>
                <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                @*  </form>*@
            </div>
        </div>
    </div>
</div>
<div id="AuditModal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Changes</h4>
            </div>
            <div class="modal-body">
                <div id="AuditModalChange"></div>
            </div>
            <div class="modal-footer">
                <form method="POST" id="AuditIdForm" class="form-horizontal" role="form" asp-anti-forgery="true">
                    <button type="button" class="btn btn-primary">Verfiy And Changes</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    function GetAuditHistory(recordID) {
        $("#audit").html("");
        var AuditDisplay = '<table class="table table-condensed" cellpadding="5">';
        var auditChangeDisplay = '<table class="table table-condensed" cellpadding="5">';
        $.getJSON("/Admin/Library/Audit/" + recordID, function (AuditTrail) {
            for (var i = 0; i < AuditTrail.length; i++) {
                AuditDisplay = AuditDisplay + '<tr class="active"><td colspan="2">Change date: ' + AuditTrail[i].DateTimeStamp + '</td>';
                auditChangeDisplay = auditChangeDisplay + '<tr class="active"><td colspan="2">Change date: ' + AuditTrail[i].DateTimeStamp + '</td>';

                AuditDisplay = AuditDisplay + '<td></td></tr>';
                //AuditDisplay = AuditDisplay + '<td>Action type: ' + AuditTrail[i].AuditActionTypeName + '</td></tr>';
                AuditDisplay = AuditDisplay + '<tr class="text-warning"><td>Changed Field</td><td>Before change</td><td colspan="2">After change</td></tr>';
                auditChangeDisplay = auditChangeDisplay + '<tr class="text-warning"><td><strong>Change Field</strong></td><td><strong>Changes</strong></td></tr>';


                for (var j = 0; j < AuditTrail[i].Changes.length; j++) {
                    AuditDisplay = AuditDisplay + '<tr>';
                    auditChangeDisplay = auditChangeDisplay + '<tr>';
                    if (AuditTrail[i].Changes[j].FieldName !== 'CreatedDate' && AuditTrail[i].Changes[j].FieldName !== 'ModifiedDate') {
                        if(AuditTrail[i].Changes[j].FieldName !== 'MultiLingual'){
                            AuditDisplay = AuditDisplay + '<td><strong>' + AuditTrail[i].Changes[j].FieldName + '</strong></td>';
                        }
                        auditChangeDisplay = auditChangeDisplay + '<td><strong>' + AuditTrail[i].Changes[j].FieldName + '</strong></td>';
}
                    if (AuditTrail[i].Changes[j].FieldName === 'ImageUrl') {
                        AuditDisplay += '<td><a href=' + AuditTrail[i].Changes[j].ValueBefore.replace("~", "") + ' class="gallery-popup"><img src=' + AuditTrail[i].Changes[j].ValueBefore.replace('~', '').replace('.jpg', '_thumb.jpg') + '></td>';
                        AuditDisplay = AuditDisplay + '<td colspan="2"><a href=' + AuditTrail[i].Changes[j].ValueAfter.replace("~", "") + ' class="gallery-popup"><img src=' + AuditTrail[i].Changes[j].ValueAfter.replace('~', '').replace('.jpg', '_thumb.jpg') + '></td>';
                        auditChangeDisplay = auditChangeDisplay + '<td><a href=' + AuditTrail[i].Changes[j].ValueAfter.replace("~", "") + ' class="gallery-popup"><img src=' + AuditTrail[i].Changes[j].ValueAfter.replace('~', '').replace('.jpg', '_thumb.jpg') + '></td>';
                    } else
                    {
                        if (AuditTrail[i].Changes[j].FieldName !== 'CreatedDate' && AuditTrail[i].Changes[j].FieldName !== 'ModifiedDate') {
                            if(AuditTrail[i].Changes[j].FieldName !== 'MultiLingual'){
                                AuditDisplay = AuditDisplay + '<td>' + AuditTrail[i].Changes[j].ValueBefore + '</td>';
                                AuditDisplay = AuditDisplay + '<td>' + AuditTrail[i].Changes[j].ValueAfter + '</td>';
                            }
                       // AuditDisplay = AuditDisplay + '<td>' + AuditTrail[i].Changes[j].Difference + '</td>';
                        auditChangeDisplay = auditChangeDisplay + '<td>' + AuditTrail[i].Changes[j].Difference + '</td>';
                    }
                    }
                    AuditDisplay = AuditDisplay + '</tr>';
                    auditChangeDisplay = auditChangeDisplay + '</tr>';
                }
            }
            AuditDisplay = AuditDisplay + '</table>';
            auditChangeDisplay = auditChangeDisplay + '</table>';
            $("#audit").html(AuditDisplay);
            $("#AuditIdForm").attr("action", "/Admin/Library/Change?id=subin");
            $("#myModal").modal('show');
            $("#AuditModalChange").html(auditChangeDisplay);
            //$("#AuditModal").modal('show');
        });
    }
    function DeleteRecord(recordID) {
        $.get("/home/delete/" + recordID);
        $('#' + recordID).remove();
    }
    function showauditmodal() {
        $("#AuditModal").modal('show');
    }
    function ShowDeleted() {
        window.location.assign('/?ShowDeleted=True');
    }
</script>

approot/src/MandirDarsan/Views/Shared/_Banner.cshtml
@using System.Threading.Tasks
@using MandirDarsan.Areas.Admin.Models
@using MandirDarsan.Models;

approot/src/MandirDarsan/Views/Shared/_BlockGod.cshtml
@using System.Threading.Tasks
@using MandirDarsan.Areas.Admin.Models
@if (ViewData["Gods"] != null)
{
    <section class="block">
        <div class="container">
            <h2 class="text-center sec-title">Gods</h2>
            <div class="row">
                @foreach (var item in ViewData["Gods"] as List<God>)
                {
                    <div class="col-md-3 col-sm-6">
                        <div class="post-list">
                            <article class="post ">
                                <div class="post-content">
                                    <figure class="post-thumb">
                                        <img src="@item.ImageUrl.Replace(".jpg","_carousel.jpg")" alt="" />
                                    </figure>
                                    <div class="entry">
                                        <h4>
                                            @try
                                            {
                                                <a href="~/@ViewContext.RouteData.Values["culture"].ToString()/Gods/Details/@item.Title.Replace(" ", "_")/@item.Id">@item.Title.Substring(0, 18)...</a>
                                            }
                                            catch (Exception)
                                            {
                                                <a href="~/@ViewContext.RouteData.Values["culture"].ToString()/Gods/Details/@item.Title.Replace(" ", "_")/@item.Id">@item.Title</a>
                                            }
                                        </h4>
                                        <p>@item.Summary</p>
                                        <a href="~/@ViewContext.RouteData.Values["culture"].ToString()/Gods/Details/@item.Title.Replace(" ", "_")/@item.Id" class="btn btn-primary"><span>Know More</span></a>
                                    </div>
                                </div>
                            </article>
                        </div>
                    </div>
                }
            </div>
        </div>
    </section>
}

approot/src/MandirDarsan/Views/Shared/_BlockProducts.cshtml
@using System.Threading.Tasks
@using MandirDarsan
@using MandirDarsan.Areas.Admin.Models;
<section class="block">
    <div class="container">
        <h2 class="text-center sec-title" translate>Related Products</h2>
        <div class="content-product row ">
            @foreach (var items in ViewData["similarproducts"] as List<Product>)
            {
                <div class="col-sm-3">
                    <div class="product-item">
                        <figure class="img-holder">
                            <img src="@items.ImageUrl.Replace(".jpg","_carousel.jpg")" alt="" />
                        </figure>
                        <div class="product-entry">
                            @if (User.IsInRole("Admin") || User.IsInRole(ViewContext.RouteData.Values["culture"].ToString() + "Contributer"))
                            {
                                <a href="~/@ViewContext.RouteData.Values["culture"].ToString()/Store/Details/@items.Title.Replace(" ", "_")/@items.Id">
                                    <h5 class="product-name">@Html.Raw(items.Title.Replace("<Translation Needed Here>", "<a href=\"/Admin/Products/Edit/" + @items.Id + "?lang=" + @ViewContext.RouteData.Values["culture"].ToString() + "\">*</a>"))</h5>
                                </a>
                            }
                            else
                            {
                                <a href="~/@ViewContext.RouteData.Values["culture"].ToString()/Store/Details/@items.Title.Replace(" ", "_")/@items.Id">
                                    <h4>
                                        @try
                                        {
                                            <a href="~/@ViewContext.RouteData.Values["culture"].ToString()/Products/Details/@items.Title.Replace(" ", "_")/@items.Id">@items.Title.Substring(0, 18)...</a>
                                        }
                                        catch (Exception)
                                        {
                                            <a href="~/@ViewContext.RouteData.Values["culture"].ToString()/Products/Details/@items.Title.Replace(" ", "_")/@items.Id">@items.Title</a>
                                        }
                                    </h4>
                                    @*<h5 class="product-name">@Html.Raw(items.Title)</h5>*@
                                </a>
                            }

                            @if (User.IsInRole("Admin") || User.IsInRole(ViewContext.RouteData.Values["culture"].ToString() + "Contributer"))
                            {
                                <p>
                                    @try
                                    {
                                        @Html.Raw(items.Summary.Replace("<Translation Needed Here>", "<a href=\"/Admin/Products/Edit/" + @items.Id + "?lang=" + @ViewContext.RouteData.Values["culture"].ToString() + "\">*</a>").Substring(0, 120))
                                    }
                                    catch (Exception)
                                    {
                                        @Html.Raw(items.Summary.Replace("<Translation Needed Here>", "<a href=\"/Admin/Products/Edit/" + @items.Id + "?lang=" + @ViewContext.RouteData.Values["culture"].ToString() + "\">*</a>"))
                                    }
                                </p>
                            }
                            else
                            {
                                <p>
                                    @Html.Raw(items.Summary.Substring(0, 100))
                                </p>
                            }
                            <span class="price">@RockmanduBase.Priceformat(items.Price.ToString())</span>
                            <div class="btn-group">
                                @*<button class="btn btn-primary" translate>Add To Cart</button>*@
                                <a asp-controller="ShoppingCart" asp-action="AddToCart" asp-route-id="@Model.Id" class="btn btn-primary" translate><span class="fa fa-shopping-cart"></span>Add to cart</a>
                                <a class="btn btn-primary" translate href="~/@ViewContext.RouteData.Values["culture"].ToString()/Store/Details/@items.Title.Replace(" ", "_")/@items.Id">View Details</a>
                            </div>
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</section>

approot/src/MandirDarsan/Views/Shared/_CreateEdit.cshtml
<link rel="stylesheet" href="~/lib/eonasdan-bootstrap-datetimepicker/build/css/bootstrap-datetimepicker.css" />
@{
    <script src="http://cdn.tinymce.com/4/tinymce.min.js"></script>
    <script>
            setTimeout(function() {
                    var divs = document.querySelectorAll("[id]");
                    for (var i = 0, len = divs.length; i < len; i++) {
                        var div = divs[i];
                        if (div.id.indexOf("Date") > -1) {
                            $('#' + div.id).datetimepicker();
                        }
                        if (div.id.indexOf("Description") > -1) {
                            $("#" + div.id).addClass("mceEditor");
                            tinyMCE.init({
                                mode: "specific_textareas",
                                editor_selector: "mceEditor"
                            });
                        }
                    }
                },
                1000)
    </script>
//await Html.RenderPartialAsync("_ValidationScriptsPartial");
}

approot/src/MandirDarsan/Views/Shared/_CultureHelper.cshtml
ng-init="culture=['English','Nepali','Hindi','Sanskrit','Chinese','Newari'];subCulture=['','Nepali','Hindi','Sanskrit','Chinese','Newari']"

approot/src/MandirDarsan/Views/Shared/_DeleteJs.cshtml
<script src="~/js/bootbox.min.js" type="text/javascript"></script>
<script>
            $('#deleteForm').on('click', '.delete-btn', function (e) {
                e.preventDefault();
                bootbox.dialog({
                    title: 'Confirm',
                    message: 'Are you sure delete this post',
                    className: 'my-class',
                    buttons: {
                        cancel: {
                            className: 'btn btn-default',
                            label: 'Close'
                        },
                        success: {
                            className: 'btn btn-success',
                            label: 'Delete',
                            callback: function () {
                                $('#deleteForm').submit();
                            }
                        }
                    }
                });
            });
            $('#EmptyTrash').on('click', '.btn-emptyTrash', function (e) {
                e.preventDefault();
                bootbox.dialog({
                    title: 'Confirm',
                    message: 'Are you sure Empty Trash?',
                    className: 'my-class',
                    buttons: {
                        cancel: {
                            className: 'btn btn-default',
                            label: 'Close'
                        },
                        success: {
                            className: 'btn btn-success',
                            label: 'Empty Trash',
                            callback: function () {
                                $('#EmptyTrash').submit();
                            }
                        }
                    }
                });
            });
</script>

approot/src/MandirDarsan/Views/Shared/_Edit - Copy.cshtml
<script>
    //alert("asdasd");
    setTimeout(function() {
            var divs = document.querySelectorAll("[id]");
            for (var i = 0, len = divs.length; i < len; i++) {
                var div = divs[i];
                if (div.id.indexOf("Nepali") > -1) {
                    if (div.id.indexOf("Description") > -1) {
                        div.value = "<p>br<p>";
                    } else {
                        div.value = "";
                    }

                }
                if (div.id.indexOf("Hindi") > -1) {
                    if (div.id.indexOf("Description") > -1) {
                        div.value = "<p>br<p>";
                    } else {
                        div.value = "";
                    }
                }
                if (div.id.indexOf("Sanskrit") > -1) {
                    if (div.id.indexOf("Description") > -1) {
                        div.value = "<p>br<p>";
                    } else {
                        div.value = "";
                    }
                }
                if (div.id.indexOf("Chinese") > -1) {
                    if (div.id.indexOf("Description") > -1) {
                        div.value = "<p>br<p>";
                    } else {
                        div.value = "";
                    }
                }
                if (div.id.indexOf("Newari") > -1) {
                    if (div.id.indexOf("Description") > -1) {
                        div.value = "<p>br<p>";
                    } else {
                        div.value = "";
                    }
                }

            }
            @*var aa = JSON.parse((@Html.Raw(@Model.MultiLingual)));
        aa.forEach(function(entry) {
            alert(entry);
        });*@
            var kk = @Html.Raw(@Model.MultiLingual);
            var obj = eval(kk);
            for (i = 0; i < obj.Tranlations.length; i++) {
                //alert(document.getElementById(obj.Tranlations[i].key).value);
                document.getElementById(obj.Tranlations[i].key).value = obj.Tranlations[i].value;
            }
        },
        1000);
</script>

approot/src/MandirDarsan/Views/Shared/_Edit.cshtml
<script>
    //alert("asdasd");
    setTimeout(function() {
            var divs = document.querySelectorAll("[id]");
            for (var i = 0, len = divs.length; i < len; i++) {
                var div = divs[i];
                if (div.id.indexOf("Nepali") > -1) {
                    if (div.id.indexOf("Description") > -1) {
                        div.value = "<p>br<p>";
                    } else {
                        div.value = "";
                    }

                }
                if (div.id.indexOf("Hindi") > -1) {
                    if (div.id.indexOf("Description") > -1) {
                        div.value = "<p>br<p>";
                    } else {
                        div.value = "";
                    }
                }
                if (div.id.indexOf("Sanskrit") > -1) {
                    if (div.id.indexOf("Description") > -1) {
                        div.value = "<p>br<p>";
                    } else {
                        div.value = "";
                    }
                }
                if (div.id.indexOf("Chinese") > -1) {
                    if (div.id.indexOf("Description") > -1) {
                        div.value = "<p>br<p>";
                    } else {
                        div.value = "";
                    }
                }
                if (div.id.indexOf("Newari") > -1) {
                    if (div.id.indexOf("Description") > -1) {
                        div.value = "<p>br<p>";
                    } else {
                        div.value = "";
                    }
                }

            }
            @*var aa = JSON.parse((@Html.Raw(@Model.MultiLingual)));
        aa.forEach(function(entry) {
            alert(entry);
        });*@
            var kk = @Html.Raw(@Model.MultiLingual);
            var obj = eval(kk);
            for (i = 0; i < obj.Tranlations.length; i++) {
                //alert(document.getElementById(obj.Tranlations[i].key).value);
                document.getElementById(obj.Tranlations[i].key).value = obj.Tranlations[i].value;
            }
        },
        1000);
</script>