approot/src/MandirDarsan/Models/ShoppingCart.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using MandirDarsan.Areas.Admin.Models;
using MandirDarsan.ViewModels.Mandir;
using Microsoft.AspNet.Antiforgery;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;

namespace MandirDarsan.Models
{
    public partial class ShoppingCart
    {

        //[FromServices]
        //public ApplicationDbContext DbContext { get; set; }

        //[FromServices]
        //public IAntiforgery Antiforgery { get; set; }

        private readonly ApplicationDbContext _dbContext;
        private string ShoppingCartId { get; set; }
        public ShoppingCart(ApplicationDbContext dbContext)
        {
            _dbContext = dbContext;
        }

        public static ShoppingCart GetCart(ApplicationDbContext db, HttpContext context)
        {
            var cart = new ShoppingCart(db);
            cart.ShoppingCartId = cart.GetCartId(context);
            return cart;
        }
        public void AddToCart(Guid productid, int qty=1)
        {
            // Get the matching cart and album instances
            var cartItem = _dbContext.Carts.SingleOrDefault(
                c => c.CartId == ShoppingCartId
                && c.ProductId == productid
                );


            if (cartItem == null)
            {
                // Create a new cart item if no cart item exists
                cartItem = new Cart
                {
                    ProductId = productid,
                    CartId = ShoppingCartId,
                    Count = qty,
                    DateCreated = DateTime.Now
                };
                _dbContext.Carts.Add(cartItem);
            }
            else
            {
                // If the item does exist in the cart, 
                // then add one to the quantity
                cartItem.Count = cartItem.Count + qty;
            }
            // Save changes
            _dbContext.SaveChanges();
        }
        public int RemoveFromCart(Guid id)
        {
            // Get the cart

            var cartItem = _dbContext.Carts.Single(
            cart => cart.CartId == ShoppingCartId
            && cart.ProductId == id);

            int itemCount = 0;

            if (cartItem != null)
            {
                if (cartItem.Count > 1)
                {
                    cartItem.Count--;
                    itemCount = cartItem.Count;
                }
                else
                {
                    _dbContext.Carts.Remove(cartItem);
                }
                // Save changes
               // _dbContext.SaveChanges();
            }
            return itemCount;
}
            public void EmptyCart()
                {
                    var cartItems = _dbContext.Carts.Where(cart => cart.CartId == ShoppingCartId).ToArray();
                    _dbContext.Carts.RemoveRange(cartItems);
                }
        public async Task<List<Cart>> GetCartItems()
        {
            var cartItems = _dbContext.Carts.
                Where(cart => cart.CartId == ShoppingCartId).
                Include(c => c.Product).
                ToListAsync();
            return await cartItems;
        }
        //public List<Cart> GetCartItems()
        //{

        //    return db.Carts.Where(
        //    cart => cart.CartId == ShoppingCartId).ToList();

        //}
        public async Task<int> GetCount()
        {
            // Get the count of each item in the cart and sum them up
            return await(from cartItem in _dbContext.Carts
                         where cartItem.CartId == ShoppingCartId
                         select cartItem.Count).SumAsync();
            //int? count = (from cartItems in db.Carts
            //              where cartItems.CartId == ShoppingCartId
            //              select (int?)cartItems.Count).Sum();
            //// Return 0 if all entries are null
            //return count ?? 0;
        }


        public async Task<decimal> GetTotal()
        {
            // Multiply album price by count of that album to get
            // the current price for each of those albums in the cart
            //  sum all album price totals to get the cart total

            decimal? total = (from cartItems in _dbContext.Carts
                              where cartItems.CartId == ShoppingCartId
                              select (int?)cartItems.Count *
                              cartItems.Product.Price).Sum();

            return total ?? decimal.Zero;


        }

        //public async Task<int> CreateOrder(Order order)
        //{
        //    decimal orderTotal = 0;

        //    var cartItems = GetCartItems();
        //    // Iterate over the items in the cart, 
        //    // adding the order details for each
        //    var orderDetail = new OrderDetail
        //    {
        //        ProductId = item.ProductId,
        //        OrderId = order.OrderId,
        //        UnitPrice = item.Price,
        //        Quantity = item.Count,
        //    };
        //    //foreach (var item in cartItems)
        //    //{
        //    //    var orderDetail = new OrderDetail
        //    //    {
        //    //        ProductId = item.ProductId,
        //    //        OrderId = order.OrderId,
        //    //        UnitPrice = item.Product.Price,
        //    //        Quantity = item.Count
        //    //    };
        //    //    // Set the order total of the shopping cart
        //    //    orderTotal += (item.Count * item.Product.Price);

        //    //    _dbContext.OrderDetails.Add(orderDetail);

        //    //}
        //    // Set the order's total to the orderTotal count
        //    order.Total = orderTotal;
        //    _dbContext.Orders.Add(order);
        //    // Save the order
        //    //_dbContext.SaveChanges();
        //    // Empty the shopping cart
        //    EmptyCart();
        //    // Return the OrderId as the confirmation number
        //    return order.OrderId;
        //}
        public async Task<Guid> CreateOrder(Order order)
        {
            decimal orderTotal = 0;

            var cartItems = await GetCartItems();

            // Iterate over the items in the cart, adding the order details for each
            foreach (var item in cartItems)
            {
                var orderDetail = new OrderDetail
                {
                    ProductId = item.ProductId,
                    OrderId = order.Id,
                    UnitPrice = item.Product.Price,
                    Quantity = item.Count,
                };
                // Set the order total of the shopping cart
                order.Total = orderTotal;
                //orderTotal += (item.Count * album.Price);

                _dbContext.OrderDetails.Add(orderDetail);
            }

            // Set the order's total to the orderTotal count
            order.Total = orderTotal;

            // Empty the shopping cart
            EmptyCart();

            // Return the OrderId as the confirmation number
            return order.Id;
        }
        private string GetCartId(HttpContext context)
        {
            var cartId = context.Session.GetString("Session");

            if (cartId == null)
            {
                //A GUID to hold the cartId. 
                cartId = Guid.NewGuid().ToString();
                // Send cart Id as a cookie to the client.
                context.Session.SetString("Session", cartId);
            }

            return cartId;
        }

        //public void MigrateCart(string userName)
        //{
        //    var shoppingCart = db.Carts.Where(
        //        c => c.CartId == ShoppingCartId);

        //    foreach (Cart item in shoppingCart)
        //    {
        //        item.CartId = userName;
        //    }
        //    db.SaveChanges();
        //}

    }

}

approot/src/MandirDarsan/Controllers/CheckoutController.cs
using System;
using System.Linq;
using System.Security.Claims;
using System.Threading;
using System.Threading.Tasks;
using MandirDarsan.Areas.Admin.Models;
using MandirDarsan.Models;
using MandirDarsan.ViewModels.Mandir;
using Microsoft.AspNet.Authorization;
using Microsoft.AspNet.Http.Internal;
using Microsoft.AspNet.Mvc;
using Microsoft.AspNet.Mvc.Rendering;
using Microsoft.Data.Entity;
namespace MandirDarsan.Controllers
{
   [Authorize]
    public class CheckoutController : Controller
    {
        [FromServices]
        public ApplicationDbContext DbContext { get; set; }
        private const string PromoCode = "FREE";
        public async Task<IActionResult> AddressAndPayment()
        {
            var cart = ShoppingCart.GetCart(DbContext, HttpContext);
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = await cart.GetCartItems(),
                CartTotal = await cart.GetTotal()
            };
            if (viewModel.CartItems.Count == 0)
            {

                return Redirect("~/Store");
                //Redirect("http://mandirdarsan.com/" + culture + "/Store");
            }
            return View(viewModel);
            //return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddressAndPayment([FromForm] Order order, CancellationToken requestAborted)
        {
            if (!ModelState.IsValid)
            {
                return View(order);
            }

            var formCollection = await HttpContext.Request.ReadFormAsync();

            try
            {
                if (string.Equals(formCollection["PromoCode"].FirstOrDefault(), PromoCode,
                    StringComparison.OrdinalIgnoreCase) == false)
                {
                    return View(order);
                }
                else
                {
                    order.Username = HttpContext.User.GetUserName();
                    order.OrderDate = DateTime.Now;

                    //Add the Order
                    DbContext.Orders.Add(order);

                    //Process the order
                    var cart = ShoppingCart.GetCart(DbContext, HttpContext);
                    await cart.CreateOrder(order);

                    // Save all changes
                    await DbContext.SaveChangesAsync(requestAborted);

                    return RedirectToAction("Complete", new { id = order.Id });
                }
            }
            catch
            {
                //Invalid - redisplay with errors
                return View(order);
            }
        }
        public async Task<IActionResult> Complete(Guid id)
        {
            // Validate customer owns this order
            bool isValid = await DbContext.Orders.AnyAsync(
                o => o.Id == id &&
                o.Username == HttpContext.User.GetUserName());

            if (isValid)
            {
                return View(id);
            }
            else
            {
                return View("Error");
            }
        }

        // GET: Checkout
        //public ActionResult Shipping()
        //{
        //    ViewBag.CountryId = new SelectList(DbContext.Countries, "CountryId", "CountryName");
        //    // Return the view
        //    //var cart = ShoppingCart.GetCart(this.HttpContext);
        //    //ViewData["Cart"] = cart.GetCartItems();
        //    //ViewData["CartTotal"] = cart.GetTotal();
        //    return View();
        //}

        //public ActionResult Complete(int id)
        //{
        //    // Validate customer owns this order
        //    bool isValid = db.Orders.Any(
        //        o => o.OrderId == id &&
        //        o.Username == User.Identity.Name);

        //    if (isValid)
        //    {
        //        return View(id);
        //    }
        //    else
        //    {
        //        return View("Error");
        //    }
        //}
        //[HttpPost]
        //public ActionResult Shipping(FormCollection values)
        //{
        //    ViewBag.CountryId = new SelectList(DbContext.Countries, "CountryId", "CountryName");
        //    //var cart = ShoppingCart.GetCart(this.HttpContext);
        //    //ViewData["Cart"] = cart.GetCartItems();
        //    //ViewData["CartTotal"] = cart.GetTotal();
        //    var order = new Order();
        //    //TryUpdateModel(order);
        //    order.Username = User.Identity.Name;
        //    order.OrderDate = DateTime.Now;

        //    //Save Order
        //    DbContext.Orders.Add(order);
        //    DbContext.SaveChanges();
        //    //Process the order

        //    //cart.CreateOrder(order);

        //    return RedirectToAction("Complete",
        //        new { id = order.OrderId });

        //}
    }
}

approot/src/MandirDarsan/Controllers/ShoppingCartController.cs
using System;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using MandirDarsan.Models;
using MandirDarsan.ViewModels.Mandir;
using Microsoft.AspNet.Antiforgery;
using Microsoft.AspNet.Http;
using Microsoft.AspNet.Http.Internal;
using Microsoft.AspNet.Mvc;
using Microsoft.Data.Entity;
using Microsoft.Extensions.Primitives;
namespace MandirDarsan.Controllers
{
    public class ShoppingCartController : Controller
    {
        [FromServices]
        public ApplicationDbContext DbContext { get; set; }
        public ShoppingCartController (ApplicationDbContext db)
        {
            DbContext = db;
        }
        [FromServices]
        public IAntiforgery Antiforgery { get; set; }

        //
        // GET: /ShoppingCart/
        public async Task<IActionResult> Index(string culture)
        {
            var cart = ShoppingCart.GetCart(DbContext, HttpContext);
            var viewModel = new ShoppingCartViewModel
            {
                CartItems = await cart.GetCartItems(),
                CartTotal = await cart.GetTotal()
            };
            if (viewModel.CartItems.Count == 0)
            {

                return Redirect("~/" + culture + "/Store");
                //Redirect("http://mandirdarsan.com/" + culture + "/Store");
            }
            return View(viewModel);
        }
        //
        // GET: /ShoppingCart/AddToCart/5
        public async Task<IActionResult> AddToCart(Guid id, int qty, CancellationToken requestAborted,IFormCollection formCollection)
        {

            // Retrieve the album from the database
            //if (qty == 0) { 
            //    qty = Convert.ToInt32(formCollection.Where(x => x.Key == "qty").Select(x => x.Value).SingleOrDefault());
            //}

            var addedAlbum = DbContext.Products
                .Single(album => album.Id == id);

            // Add it to the shopping cart
            var cart = ShoppingCart.GetCart(DbContext, HttpContext);

           // cart.AddToCart(addedAlbum.ProductId,qty);
            if (qty == 0)
            {
                qty = 1;
            }
            cart.AddToCart(addedAlbum.Id, qty);

            await DbContext.SaveChangesAsync(requestAborted);

            // Go back to the main store page for more shopping
            return RedirectToAction("Index");
        }

        //
        // AJAX: /ShoppingCart/RemoveFromCart/5
        [HttpPost]
        public async Task<IActionResult> RemoveFromCart(Guid id, CancellationToken requestAborted)
        {
            var cookieToken = string.Empty;
            var formToken = string.Empty;
            StringValues tokenHeaders;
            string[] tokens = null;

            if (HttpContext.Request.Headers.TryGetValue("RequestVerificationToken", out tokenHeaders))
            {
                tokens = tokenHeaders.First().Split(':');
                if (tokens != null && tokens.Length == 2)
                {
                    cookieToken = tokens[0];
                    formToken = tokens[1];
                }
            }
            try
            {
                Antiforgery.ValidateTokens(HttpContext, new AntiforgeryTokenSet(formToken, cookieToken));
            }
            catch (Exception)
            {
            }
            

            var cart = ShoppingCart.GetCart(DbContext, HttpContext);
            try
            {
                var cartItem = DbContext.Carts
                    .Where(item => item.ProductId == id).Include(x=>x.Product);
               
           
           

            int itemCount = cart.RemoveFromCart(id);

            await DbContext.SaveChangesAsync(requestAborted);

            string removed = (itemCount > 0) ? " 1 copy of " : string.Empty;
            
            var results = new ShoppingCartRemoveViewModel
            {
                Message = removed + /*cartItem.Product.Title +*/
                    " has been removed from your shopping cart.",
                CartTotal = await cart.GetTotal(),
                CartCount = await cart.GetCount(),
                ItemCount = itemCount,
                DeleteId = id
            };
                return Json(results);
            }
            catch (Exception ex)
            {

                throw;
            }
           
        }
    }
}

approot/src/MandirDarsan/Views/ShoppingCart/Cart.cshtml
@*<section class="block title-sec">
<div class="container">
    <h1 class="page-toitle">Checkout</h1>
    <ul class="breadcrumb">
        <li><a href="index">Home</a></li>
        <li>Checkout</li>
    </ul>
</div>
            </section>*@
@Html.Partial("_Breadcrumb")
<section class="block block-light">
    <div class="container">
        <div class="">
            <div class="page-header">
                <div class="heading-description">
                    <h6 translate>Review Your cart</h6>
                </div>
            </div>
            <div class="">
                <table class="table table-hover table-common table-cart">
                    <thead>
                        <tr>
                            <th translate>
                                Images
                            </th>
                            <th translate>
                                Product Name
                            </th>
                            <th translate>
                                Unit Price
                            </th>
                            <th translate>
                                Quantity
                            </th>
                            <th translate>
                                Total
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr id="row-item.RecordId">
                            <td>
                                <div class="product-thumbnail">
                                    <img width="90" height="90" src="http://www.sampression.com/wp-content/uploads/sampression-pro-thumbnail-90x90.png">
                                </div>
                            </td>
                            <td>
                                Product
                            </td>
                            <td>
                                1000
                            </td>
                            <td id="item-count-item.RecordId">
                                2
                            </td>
                            <td id="item-count-item.RecordId">
                                2000
                            </td>
                            <td>

                                <a href="RemoveFromCart" class="fa fa-times icon-delete" data-id="asd">

                                </a>
                            </td>
                        </tr>
                        <!--    <tr>
                            <td>
                                Total
                            </td>
                            <td>
                                @Html.ActionLink("Empty Cart",
                            "EmptyCart", "Store", null)
                            </td>
                            <td>
                                <a href="~/checkout/shipping">Checkout</a>
                            </td>
                            <td id="cart-total">
                                Model.GetTotal
                            </td>
                        </tr>* -->
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="6" class="actions">

                                <div class="coupon">
                                    <input type="text" name="coupon_code" class="input-text form-control col-xs-5" id="coupon_code" value="" translate translate-attr-placeholder="Coupon code">
                                    <input type="submit" class="btn  button" name="apply_coupon" value="Apply Coupon">
                                </div>
                            </td>
                        </tr>
                    </tfoot>

                </table>


            </div>
            <div class="cart-totals">


                <h2>Cart Totals</h2>

                <table cellspacing="0" class="table table-common">

                    <tbody>
                        <tr class="cart-subtotal">
                            <th translate>Subtotal</th>
                            <td><span class="amount">$&nbsp;49.00</span> / year</td>
                        </tr>

                        <tr class="order-total">
                            <th translate>Total</th>
                            <td><strong><span class="amount">$&nbsp;49.00</span> / year</strong> </td>
                        </tr>


                    </tbody>
                </table>


                <div class="wc-proceed-to-checkout pull-right">

                    <a href="~/cart/checkout" class="btn btn-primary" translate>Proceed to Checkout</a>

                </div>


            </div>
        </div>

    </div>
</section>
    
  

approot/src/MandirDarsan/Views/ShoppingCart/Index.cshtml
@using ImageResizer.ExtensionMethods
@model MandirDarsan.ViewModels.Mandir.ShoppingCartViewModel
@inject Microsoft.AspNet.Antiforgery.IAntiforgery Xsrf
@{
    ViewBag.Title = "Shopping Cart";
}
@functions
{
    public string GetAntiXsrfToken()
    {
        var tokens = Xsrf.GetTokens(Context);
        return tokens.CookieToken + ":" + tokens.FormToken;
    }
}
@section Scripts {
    <script type="text/javascript">
        $(function () {
            // Document.ready -> link up remove event handler
            $(".RemoveLink").click(function () {
               // alert("asdas");
                // Get the id from the link
                var recordToDelete = $(this).attr("data-id");
                var PostToUrl = $(this).attr("data-url");
               // a//lert(PostToUrl);
                if (recordToDelete != '') {
                   // alert(recordToDelete);
                    // Perform the ajax post
                    $.ajax(PostToUrl, {
                        type: "post",
                        data: { "id": recordToDelete },
                        dataType: "json",
                        headers: {
                            "RequestVerificationToken": '@GetAntiXsrfToken()'
                        }
                    }).done(function (data) {
                        //alert(data.DeleteId);
                        location.reload();
                        if (data.ItemCount == 0) {
                            $('#row-' + data.DeleteId).fadeOut('slow');
                        } else {
                            $('#item-count-' + data.DeleteId).text(data.ItemCount);
                        }

                        $('#cart-total').text(data.CartTotal);
                        $('#update-message').text(data.Message);
                        $('#cart-status').text('Cart (' + data.CartCount + ')');
                    });
                }
            });

        });
    </script>
}
<section class="block title-sec">
    <div class="container">
        <h1 class="page-toitle" translate>Checkout</h1>
        <ul class="breadcrumb" translate>
            <li><a href="index" translate>Home</a></li>
            <li translate>Checkout</li>
        </ul>
    </div>
</section>
<section class="block block-light">
    <div class="container">
        <div class="">
            <div class="page-header">
                <div class="heading-description">
                    <h6 translate>Review Your cart</h6>
                </div>
            </div>
            <div class="">
                <table class="table table-hover table-common table-cart">
                    <thead>
                        <tr>
                            <th translate>
                                Image
                            </th>
                            <th translate>
                                Product
                            </th>
                            <th translate>
                                Unit Price
                            </th>
                            <th translate>
                                Quantity
                            </th>
                            <th translate>
                                Total
                            </th>
                            <th>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                    @foreach (var item in Model.CartItems)
                    {
                        <tr id="row-@item.CartId">
                            <td>
                                <div class="product-thumbnail">
                                    <img width="90" height="90" src="@item.Product.ImageUrl">
                                </div>
                            </td>
                            <td>
                               @item.Product.Title
                            </td>
                            <td>
                                    @item.Product.Price
                            </td>
                            <td id="item-count-item.RecordId">
                                    @item.Count
                                </td>
                            <td id="item-count-item.RecordId">
                                    {{@item.Count * @item.Product.Price}}
                            </td>
                            <td>
                                <a href="#" class="RemoveLink" data-id="@item.ProductId"
                                   data-url='@Url.Content("~/English/ShoppingCart/RemoveFromCart")' translate>
                                    Remove from cart
                                </a>
                             </td>
                        </tr>
                    }
                    <!-- <tr>
                        <td>
                            Total
                        </td>
                        <td>
                            @Html.ActionLink("Empty Cart",
                                "EmptyCart", "Store", null)
                        </td>
                        <td>
                            <a href="~/checkout/shipping">Checkout</a>
                        </td>
                        <td id="cart-total">
                            Model.GetTotal
                        </td>
                    </tr>* -->
                    </tbody>
                    <tfoot>
                        <tr>
                            <td colspan="6" class="actions">
                                <div class="coupon">
                                    <input type="text" name="coupon_code" class="input-text form-control col-xs-5" id="coupon_code" value="" translate translate-attr-placeholder="Coupon code">
                                    <input type="submit" class="btn  button" name="apply_coupon" value="Apply Coupon">
                                </div>
                            </td>
                        </tr>
                    </tfoot>
                </table>
            </div>
            <div class="cart-totals">
                <h2 translate>Cart Totals</h2>
                <table cellspacing="0" class="table table-common">

                    <tbody>
                        <tr class="cart-subtotal">
                            <th translate>Subtotal</th>
                            @try
                            {
                                <td><span class="amount">@Model.CartTotal</span></td>
                            }
                            catch (Exception)
                            {

                            }
    
                        </tr>

                        <tr class="order-total">
                            <th translate>Total</th>
                            @try
                            {
                                <td><strong><span class="amount">@Model.CartTotal</span></strong> </td>
                            }
                            catch (Exception)
                            {


                            }
                       </tr>
                    </tbody>
                </table>
                <div class="wc-proceed-to-checkout pull-right">
                        <a asp-controller="Checkout" asp-action="AddressAndPayment" class="btn btn-primary" translate>Checkout</a>
                </div>
            </div>
        </div>
    </div>
</section>